import Head from "next/head";
// import styles from "../../styles/Home.module.css";
import styles from "./Layout.module.css"

const Layout =({children, title = "World Ranks"}) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main className={styles.main}>
            {children}
          </main>
    
          <footer className={styles.footer}>
            footer
          </footer>
        </div>
      )
}

export default Layout;